tap "homebrew/cask"
tap "buo/cask-upgrade"

brew "node"
brew "z"
brew "git"
brew "git-recent"
brew "bash-completion"
brew "fzf"

cask "docker"
cask "appcleaner"
cask "slack"
cask "kaleidoscope"
cask "rectangle"
cask "insomnia"
cask "spotify"
cask "tableplus"
cask "table-tool"